[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "E5kv2j41SfsrZyCeEohk8SQ3i71Yzgiv32ey8ekeL5mQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
